[package]
name = "guild-sc-config-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.guild-sc-config]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "=0.52.3"
default-features = false
