[package]
name = "guild-factory-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.guild-factory]
path = ".."

[dependencies.multiversx-sc-meta]
version = "=0.47.5"
default-features = false
