default_api = "https://express-api-shadowfork-four.elrond.ro"
default_proxy = "https://proxy-shadowfork-four.elrond.ro"
deployed_guild_address = "erd1qqqqqqqqqqqqqpgqquen99qztefk9ms5pu858xvq5ywn7alpkg2sw03j2r"
division_safety_constant = "10000000000000000000"
farmingToken = "TESTUTK-477d07"
guildConfigBYTEPATH = "/home/multiversx/Documents/guilds_py/wasm/guild-sc-config.wasm"
guildConfigScAddressModel = "erd1qqqqqqqqqqqqqpgqp2xsy9gxd0me9h2u5jjhs25dtvlv0uhmkg2s5elha2"
guildFactoryBYTEPATH = "/home/multiversx/Documents/guilds_py/wasm/guild-factory.wasm"
guildFactoryScAddress = "erd1qqqqqqqqqqqqqpgqqgjvhefmnevtxcajf9550ecjunk0dmtqkg2s0uhlrf"
guildSCBYTEPATH = "/home/multiversx/Documents/guilds_py/wasm/guild-sc.wasm"
guildScAddressModel = "erd1qqqqqqqqqqqqqpgq0aurxguzpsd5eetwj9cjfhp2ewup4lvmkg2sprafnd"
perBlockRewardAmount = "40000000000000000"
signingWalletAddress = "erd1a2x0azarwsag9svwdn23pjramat7zcjceqd44yh4g7jx4pugkg2s3jwlel"
signingWalletPemPath = "./../defi-wallet.pem"
